AllCops:
  # 除外
  Exclude:
    - "vendor/**/*"
    - "bin/**/*"
    - "db/**/*"
    - "tmp/**/*"
    - "node_modules/**/*"
    - "spec/**/*"

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

# クラスのコメント必須を無視
Style/Documentation:
  Enabled: false

# モジュール名::クラス名の定義を許可
Style/ClassAndModuleChildren:
  Enabled: false

# 文字リテラルのイミュータブル宣言を無視（freezeになるのはRuby3以降）
Style/FrozenStringLiteralComment:
  Enabled: false

# コントローラのメソッド名に「set_」「get_」を許可
Naming/AccessorMethodName:
  Exclude:
    - "app/controllers/**/*"

Metrics/BlockLength:
  Exclude:
    - "config/**/*"

# 緩めに設定する
Metrics/AbcSize:
  Max: 30   #default 15
  Exclude:
    - "app/forms/*.rb"

# 一行の長さは１５０文字まで。 コメントは制限しない
Layout/LineLength:
  Max: 150
  IgnoredPatterns: ["^ *# "]
  Exclude:
    - "db/migrate/*.rb"

# メソッドの行数は２０行まで
Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/migrate/*.rb"
