version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
  web:
    build: ./api
    command: bundle exec puma -C config/puma.rb
    volumes:
      - ./api:/myapp
      - bundle_path:/bundle
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - log-data:/var/log/nginx
    environment:
      - EDITOR=vim
      - BUNDLE_PATH=/bundle
    ports:
      - '3000:3000'
    links:
      - db
    tty: true
    stdin_open: true
  front:
    build: ./front
    volumes:
      - ./front:/myapp
    environment:
      - VUE_APP_API_ENDPOINT=http://localhost
    ports:
      - '8080:8080'
    tty: true
    stdin_open: true
    command: yarn serve
  nginx:
    build:
      context: ./api/containers/nginx
    ports:
      - '80:80'
    volumes:
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
    depends_on:
      - web
  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - '8025:8025'
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - maildir:/tmp
volumes:
  bundle_path:
  public-data:
  tmp-data:
    driver: local
  log-data:
    driver: local
  maildir:
  mysql-data:
    driver: local