check_name: 'Rubocop Results'
versions:
  - rubocop: '0.83.0'
  - rubocop-rails: '2.5.2'
  - rubocop-performance: '1.5.2'
  - rubocop-rspec: '1.39.0'
rubocop_config_path: './api/.rubocop.yml'
rubocop_force_exclusion: true
check_scope: 'modified'