check_name: 'Rubocop Results'
versions:
  - rubocop
  - rubocop-rails
  - rubocop-performance: "1.5.1"
  - rubocop-minitest: "latest"
  - rubocop-rspec: "1.37.0"
rubocop_config_path: '.rubocop.yml'
rubocop_force_exclusion: true
check_scope: 'modified'