name: github push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      DB_HOST: 127.0.0.1

    services:
      db:
        image: mysql:8.0
        volumes:
          - mysqlconf.d:/etc/mysql/conf.d
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: actions_test

    strategy:
      matrix:
        ruby-version: ['3.0']

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true 
      
      - name: apt-get
        run: |
          sudo apt-get update
          sudo apt-get install libmysqlclient-dev
      
      - name: RuboCop Linter Action
        uses: andrewmcodes-archive/rubocop-linter-action@v3.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Rubocop checks
        run: bundle exec rubocop

      - name: Rails Best Practices
        run: bundle exec rails_best_practices

      - name: Setup Database
        run: |
          mv config/database.ci.yml config/database.yml
          bundle exec rails db:create
          bundle exec rails db:schema:load

      - name: Rspec
        run: bundle exec rspec

      - name: slack - GitHub Actions Slack integration
        uses: act10ns/slack@v1.2.2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          