name: rails

on: push

env: 
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_CHANNEL: github-actions
  RAILS_ENV: test
  DB_HOST: 127.0.0.1
  BACKTRACE: true

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      github_test:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_USER: root
        volumes:
          - mysqlconf.d:/etc/mysql/conf.d
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
        with:
          ruby-version: 3.0
          bundler-cache: true 

      - name: rubocop
        run: bundle exec rubocop

      - name: set database.yml
        run: mv config/database.ci.yml config/database.yml
      
      - name: db create
        run: |
          bundle exec rails db:create 
          bundle exec rails db:schema:load
      
      - name: run rspec
        run: bundle exec rspec

      - name: Slack Notification on Success
        if: success()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_TITLE: Test Success
          SLACK_COLOR: good

      - name: Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2.0.2
        if: failure()
        env:
          SLACK_TITLE: Test Failure
          SLACK_COLOR: danger
